relative_permalinks: false
google_analytics_id: UA-11634531-4
gauges_id: 
permalink: /news/:year/:month/:day/:title
safe: true
lsi: false
highlighter: pygments
markdown: kramdown

slides:
    version: 1.5
    executable: java -jar sikuli-slides-1.5.0.jar
    example_exec: java -cp sikuli-slides-1.5.0.jar
    executable_download: http://slides.sikuli.org/sikuli-slides-1.5.0.jar
    helloworld_download: http://slides.sikuli.org/helloworld.pptx